### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by pdurbin** [Greenheart/greenheart.github.io#1]
"I am an 19-year-old orienteer..." should be "I am a 19-year-old orienteer..."

I noticed http://samuelplumppu.se via https://raviloop.github.io via https://gitter.im/gitterHQ/gitter?at=5830518f5eb8ea792a3d1a0a by @raviloop

**Comment by Greenheart** [comment]
@pdurbin Haha thanks for the notice! :smile: 

I read about this and realized I've been wrong about a/an for a long time. You learn every day i guess!

Have a nice day!
